project_id = "fonfzwbbyluurdusytwu"

[api]
enabled = true

[auth]
enabled = true

[functions.configure]
verify_jwt = true

[functions.synthesize]
verify_jwt = true

[functions.simulate]
verify_jwt = true
