import type { CandidateSummary } from '../../lib/types';

interface CandidateSummaryCardProps {
  summary: CandidateSummary;
  agentName?: string;
}

function interestColor(level: CandidateSummary['interest_level']) {
  if (level === 'high') return 'bg-teal';
  if (level === 'medium') return 'bg-amber-400';
  return 'bg-coral';
}

export function CandidateSummaryCard({
  summary,
  agentName = 'Agent',
}: CandidateSummaryCardProps) {
  const scorePct = Math.round((summary.engagement_score ?? 0) * 100);

  return (
    <div className="rounded-lg border border-line bg-app-card p-5">
      <div className="mb-4 flex items-start justify-between gap-3">
        <p className="text-xs font-medium uppercase tracking-wider text-fg-secondary">
          Candidate summary
        </p>
        <p className="text-xs text-fg-tertiary">Generated by {agentName}</p>
      </div>

      <div className="mb-5">
        <div className="mb-2 flex items-center justify-between gap-3">
          <span className="text-sm text-fg-primary">
            Interest: {scorePct}%
          </span>
          <span className="text-sm text-fg-secondary">{summary.interest_label}</span>
        </div>
        <div className="h-2 overflow-hidden rounded-full bg-app-raised">
          <div
            className={`h-full rounded-full transition-all ${interestColor(summary.interest_level)}`}
            style={{ width: `${scorePct}%` }}
          />
        </div>
      </div>

      <div className="mb-4 grid gap-4 sm:grid-cols-2">
        <div>
          <p className="mb-2 text-xs font-medium uppercase text-fg-secondary">
            Motivators
          </p>
          <ul className="space-y-1">
            {summary.key_motivators.map((item) => (
              <li key={item} className="flex gap-2 text-sm text-fg-primary">
                <span className="text-teal">✓</span>
                {item}
              </li>
            ))}
          </ul>
        </div>
        <div>
          <p className="mb-2 text-xs font-medium uppercase text-fg-secondary">
            Concerns
          </p>
          <ul className="space-y-1">
            {summary.concerns.map((item) => (
              <li key={item} className="flex gap-2 text-sm text-fg-primary">
                <span className="text-coral">!</span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="mb-4">
        <p className="mb-2 text-xs font-medium uppercase text-fg-secondary">
          Signals
        </p>
        <ul className="space-y-1">
          {summary.signals_detected.map((item) => (
            <li key={item} className="text-sm text-fg-secondary">
              • {item}
            </li>
          ))}
        </ul>
      </div>

      <div className="mb-4 rounded-lg bg-app-secondary p-3">
        <p className="mb-1 text-xs font-medium uppercase text-fg-secondary">
          Recommended next step
        </p>
        <p className="text-sm text-fg-primary">{summary.recommended_next_step}</p>
      </div>

      {(summary.objections_raised.length > 0 ||
        summary.objections_resolved.length > 0) && (
        <p className="text-xs text-fg-tertiary">
          Objections:{' '}
          {summary.objections_raised
            .map((o) =>
              summary.objections_resolved.includes(o)
                ? `${o} (resolved)`
                : `${o} (unresolved)`,
            )
            .join(', ')}
        </p>
      )}
    </div>
  );
}
